##  -*-  coding: utf-8; mode: ruby -*-  ##
##  vi: set ft=ruby

load  File.expand_path("DetectOS.rb")  if File.exists?("DetectOS.rb")

Vagrant.configure("2") do |config|
  config.vm.box = "takahiro-itou/ubuntu-focal64-gui"

  config.vm.provider "virtualbox" do |v|
    v.name   = "vagrant-ubuntu-gui"
    v.memory = "3072"

    v.gui    = true
    v.customize [
      "modifyvm",           :id,
      "--cableconnected1",  "on",
      "--hwvirtex",         "on",
      "--nestedpaging",     "on",
      "--largepages",       "on",
      "--ioapic",           "on",
      "--pae",              "on",
      "--paravirtprovider", "kvm",
    ]
  end

  config.vm.boot_timeout = 900

  config.vm.network(:forwarded_port, guest: 22, host: 11122, id: "ssh")
  config.vm.network("private_network", ip: "192.168.33.11")

  config.vm.provision("userfiles1", type: "file",
                      source: "../data/",
                      destination: "/tmp/")

  config.vm.provision("root", type: "shell",
                      path: "provision.root.sh",
                      privileged: true)
  config.vm.provision("user", type: "shell",
                      path: "provision.user.sh",
                      privileged: false)
  config.vm.provision("hguser", type: "shell",
                      path: "provision.hguser.sh",
                      privileged: false)
  config.vm.synced_folder(".", "/vagrant", disabled: true)

end
